# Generated by Django 4.2.7 on 2023-11-20 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id especialidad')),
                ('nombreEspecialidad', models.CharField(max_length=80, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=80, null=True, verbose_name='Rut')),
                ('direccion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección')),
                ('rol', models.CharField(blank=True, max_length=1, null=True, verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=80, verbose_name='Fecha atención')),
                ('doctor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doctor a cargo')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cmg.especialidad')),
            ],
        ),
    ]
