# Generated by Django 4.2.7 on 2023-11-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencionmedica',
            name='precio',
        ),
    ]
