# Generated by Django 4.2.7 on 2023-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmg', '0003_alter_atencionmedica_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMedica',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doctor a cargo')),
            ],
        ),
    ]
